# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExactnessPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(799, 599)
        self.mXYInput = QtWidgets.QLineEdit(Form)
        self.mXYInput.setGeometry(QtCore.QRect(200, 160, 411, 41))
        self.mXYInput.setObjectName("mXYInput")
        self.nXYInput = QtWidgets.QLineEdit(Form)
        self.nXYInput.setGeometry(QtCore.QRect(200, 240, 411, 41))
        self.nXYInput.setObjectName("nXYInput")
        self.checkForExactness = QtWidgets.QPushButton(Form)
        self.checkForExactness.setGeometry(QtCore.QRect(320, 300, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkForExactness.setFont(font)
        self.checkForExactness.setDefault(True)
        self.checkForExactness.setObjectName("checkForExactness")
        self.backToMenu = QtWidgets.QPushButton(Form)
        self.backToMenu.setGeometry(QtCore.QRect(330, 410, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backToMenu.setFont(font)
        self.backToMenu.setDefault(True)
        self.backToMenu.setObjectName("backToMenu")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 50, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(380, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(380, 210, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.resultText = QtWidgets.QLabel(Form)
        self.resultText.setGeometry(QtCore.QRect(10, 350, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultText.setFont(font)
        self.resultText.setAlignment(QtCore.Qt.AlignCenter)
        self.resultText.setObjectName("resultText")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Check Exactness"))
        self.checkForExactness.setText(_translate("Form", "Check Exactness"))
        self.backToMenu.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "Exactness Checking"))
        self.label_2.setText(_translate("Form", "M(x,y)"))
        self.label_3.setText(_translate("Form", "N(x,y)"))
        self.resultText.setText(_translate("Form", "Results are shown here."))
