# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomogeneityPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(799, 599)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 751, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(370, 250, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.nXYInput = QtWidgets.QLineEdit(Form)
        self.nXYInput.setGeometry(QtCore.QRect(190, 280, 411, 41))
        self.nXYInput.setObjectName("nXYInput")
        self.resultText = QtWidgets.QLabel(Form)
        self.resultText.setGeometry(QtCore.QRect(10, 390, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultText.setFont(font)
        self.resultText.setAlignment(QtCore.Qt.AlignCenter)
        self.resultText.setObjectName("resultText")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(370, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.checkForHomogeneity = QtWidgets.QPushButton(Form)
        self.checkForHomogeneity.setGeometry(QtCore.QRect(320, 350, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkForHomogeneity.setFont(font)
        self.checkForHomogeneity.setDefault(True)
        self.checkForHomogeneity.setObjectName("checkForHomogeneity")
        self.backToMenu = QtWidgets.QPushButton(Form)
        self.backToMenu.setGeometry(QtCore.QRect(330, 440, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backToMenu.setFont(font)
        self.backToMenu.setDefault(True)
        self.backToMenu.setObjectName("backToMenu")
        self.mXYInput = QtWidgets.QLineEdit(Form)
        self.mXYInput.setGeometry(QtCore.QRect(190, 200, 411, 41))
        self.mXYInput.setObjectName("mXYInput")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Check Homogeneity and Degree"))
        self.label.setText(_translate("Form", "Homogeneity and Degree Checking"))
        self.label_3.setText(_translate("Form", "N(x,y)"))
        self.resultText.setText(_translate("Form", "Results are shown here."))
        self.label_2.setText(_translate("Form", "M(x,y)"))
        self.checkForHomogeneity.setText(_translate("Form", "Check Homogeneity"))
        self.backToMenu.setText(_translate("Form", "Back"))
