# Author @Adim
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 50, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 170, 311, 113))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkExactness = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkExactness.setFont(font)
        self.checkExactness.setAutoDefault(False)
        self.checkExactness.setDefault(True)
        self.checkExactness.setFlat(False)
        self.checkExactness.setObjectName("checkExactness")
        self.verticalLayout.addWidget(self.checkExactness)
        self.checkHomogeneity = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkHomogeneity.setFont(font)
        self.checkHomogeneity.setAcceptDrops(False)
        self.checkHomogeneity.setAutoDefault(False)
        self.checkHomogeneity.setDefault(True)
        self.checkHomogeneity.setFlat(False)
        self.checkHomogeneity.setObjectName("checkHomogeneity")
        self.verticalLayout.addWidget(self.checkHomogeneity)
        self.exitProgram = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exitProgram.setFont(font)
        self.exitProgram.setDefault(True)
        self.exitProgram.setObjectName("exitProgram")
        self.verticalLayout.addWidget(self.exitProgram)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Differentional Equation Analyzer"))
        self.label.setText(_translate("MainWindow", "Choose an Option"))
        self.checkExactness.setText(_translate("MainWindow", "Check Exactness"))
        self.checkHomogeneity.setText(_translate("MainWindow", "Check Homogeneity and Degree"))
        self.exitProgram.setText(_translate("MainWindow", "Exit"))
